[package]
name = "aes"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "0.8.7", features = ["boolean", "shortint", "integer", "x86_64-unix", "gpu"] }
rand = "0.8"
aes = "0.8.4"
rayon = "1.7"