[package]
name = "aes"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "0.11.2", features = ["boolean", "shortint", "integer", "experimental"] }
rand = "0.8"
aes = "0.8.4"
rayon = "1.7"
